# Generated by Django 5.0.6 on 2024-09-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_our_community_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourcommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ourcommunity')),
            ],
        ),
        migrations.DeleteModel(
            name='our_community',
        ),
    ]
